CREATE TABLE PUBLIC.LOCATION(
    ID serial primary key, 
    COUNTRY VARCHAR(255),
    STATE VARCHAR(255)
);     

CREATE TABLE PUBLIC.MANUFACTURER(
    ID serial primary key,
    AVERAGEYEARLYSALES DECIMAL(19, 2),
    FOUNDEDDATE TIMESTAMP,
    NAME VARCHAR(255),
    HEADQUARTERS_ID BIGINT,
    LOCATION_ID BIGINT,
    ACTIVE BOOLEAN
);      
        

CREATE TABLE PUBLIC.MODEL(
    ID serial primary key,
    FRETS INTEGER NOT NULL,
    NAME VARCHAR(255),
    PRICE DECIMAL(19, 2),
    WOODTYPE VARCHAR(255),
    YEARFIRSTMADE TIMESTAMP,
    MANUFACTURER_ID BIGINT,
    MODELTYPE_ID BIGINT
);
 

CREATE TABLE PUBLIC.MODELTYPE(
    ID serial primary key,
    NAME VARCHAR(255)
);               
               

ALTER TABLE PUBLIC.MANUFACTURER ADD FOREIGN KEY(LOCATION_ID) REFERENCES PUBLIC.LOCATION(ID);       
ALTER TABLE PUBLIC.MODEL ADD FOREIGN KEY(MANUFACTURER_ID) REFERENCES PUBLIC.MANUFACTURER(ID);      
ALTER TABLE PUBLIC.MODEL ADD FOREIGN KEY(MODELTYPE_ID) REFERENCES PUBLIC.MODELTYPE(ID);            
ALTER TABLE PUBLIC.MANUFACTURER ADD FOREIGN KEY(HEADQUARTERS_ID) REFERENCES PUBLIC.LOCATION(ID);  
